---
title: "ISSS608-VAA"
---

welcome to ISSS608 Visual Analytics and Applications.I am ***xhwang0226***.

This website showcases my hands-on exercises and learning journey through the course. Each exercise explores different visualization techniques using R, Quarto, and various visualization packages.

## Hands-on Exercises

-   [Hands-on Exercise 1: A Layered Grammar of Graphics with ggplot2](Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html)
-   [Hands-on Exercise 2: Beyond ggplot2 Fundamentals](Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html)
-   [Hands-on Exercise 3_1: Programming Interactive Data Visualisation](Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html)
-   [Hands-on Exercise 3_2: Programming Animated Statistical Graphics](Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html)
-   [Hands-on Exercise 4_1: Visualising Distribution](Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_01.html)
-   [Hands-on Exercise 4_2: Visual Statistical Analysis](Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_02.html)
-   [Hands-on Exercise 4_3: Visualising Uncertainty](Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_03.html)
-   [Hands-on Exercise 4_4: Funnel Plots for Fair Comparisons](Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_04.html)
-   [Hands-on Exercise 5_1: Creating Ternary Plot with R](Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_01.html)
-   [Hands-on Exercise 5_2: Visual Correlation Analysis R](Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_02.html)
-   [Hands-on Exercise 5_3:  Heatmap for Visualising and Analysing Multivariate Data R](Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_03.html)
-   [Hands-on Exercise 5_4: Visual Multivariate Analysis with Parallel Coordinates Plot R](Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_04.html)
-   [Hands-on Exercise 5_5: Treemap Visualisation with R R](Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_04.html)
