---
title: "Hands-on_Ex04_04"
author: "Wang Xiaohan"
date: "May 8, 2026"
date-modified: "last-modified"
format: 
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
execute: 
  echo: true
  eval: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(readxl, SmartEDA, tidyverse,
               ggstatsplot, easystats, tidymodels)
```


```{r}
car_resale <- read_xlsx("data/ToyotaCorolla.xlsx",
                        sheet = "data")
```

```{r}
ExpCatStat(car_resale,
           Target = "Price",
           result = "Stat")
```


```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + 
              Weight + Guarantee_Period, data = car_resale)
model
```

```{r}
check_collinearity(model)
```

```{r}
check_c <- check_collinearity(model)
plot(check_c)
```

```{r}
model1 <- lm(Price ~ Age_08_04 + KM + 
              Weight + Guarantee_Period, data = car_resale)
```
```{r}
check_n <- check_normality(model1)
```
```{r}
plot(check_n)
```

```{r}
check_h <- check_heteroscedasticity(model1)
```
```{r}
plot(check_h)
```

```{r}
check_model(model1)
```

```{r}
plot(parameters::parameters(model1))
```

```{r}
ggcoefstats(model1, 
            output = "plot")
```

